### PR TITLE
Athena can only pull 999 rows at a time

### PR DESCRIPTION
**Pull request by daroczig**

### CODE REVIEW

**Comment by nfultz** [comment]
Yeck, RJDBC needs to get updated to use new DBI - 

I think it makes more sense to implement `dbFetch` here than `dbGetQuery`, otherwise things might work inconsistently across the package.


In the dbFetch implementation, you should be able to calculate block size a la:
 with `block = if(n < 0) 999 else pmin(n, 999)`

and then delegate the request back to RJDBC::fetch with the smaller block size.


See also [1] and [2]

[1] https://github.com/s-u/RJDBC/blob/master/java/JDBCResultPull.java#L69
[2] https://github.com/s-u/RJDBC/blob/master/R/class.R#L328

**Comment by nfultz** [comment]
Also is this 999 limitation documented anywhere?

**Comment by nfultz** [comment]
Ah https://github.com/s-u/RJDBC/issues/44

**Comment by daroczig** [comment]
I'd like to get `dbGetQuery` working on Athena, and as `dbGetQuery` has a harcoded 2K set for the blocksize, I don't really see any other easy way. This PR required more commits than I originally hoped :) But seems to work fine now.

**Comment by daroczig** [comment]
@nfultz pls feel free to tweak this further, I don't really want to start hacking `fetch` instead

**Comment by daroczig** [comment]
Closing in favour of #9

**Pull request closed without merging**
